---
files:
  - 'lib/libplatform/drivers/mss/mss_spi/mss_spi.c'
  - 'lib/libplatform/drivers/mss/mss_gpio/mss_gpio.c'
  - 'lib/libplatform/drivers/mss/mss_rtc/mss_rtc.c'
  - 'lib/libplatform/drivers/mss/mss_mmuart/mss_uart.c'
  - 'lib/libplatform/drivers/mss/mss_sys_services/mss_sys_services.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_cfm.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_ddr.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_ddr_debug.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_ddr_test_pattern.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_io.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_nwc_init.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_pll.c'
  - 'lib/libplatform/mpfs_hal/common/nwc/mss_sgmii.c'
  - 'lib/libplatform/mpfs_hal/common/mss_beu.c'
  - 'lib/libplatform/mpfs_hal/common/mss_clint.c'
  - 'lib/libplatform/mpfs_hal/common/mss_irq_handler_stubs.c'
  - 'lib/libplatform/mpfs_hal/common/mss_l2_cache.c'
  - 'lib/libplatform/mpfs_hal/common/mss_mpu.c'
  - 'lib/libplatform/mpfs_hal/common/mss_mtrap.c'
  - 'lib/libplatform/mpfs_hal/common/mss_peripherals.c'
  - 'lib/libplatform/mpfs_hal/common/mss_plic.c'
  - 'lib/libplatform/mpfs_hal/common/mss_pmp.c'
  - 'lib/libplatform/mpfs_hal/common/mss_util.c'
  - 'lib/libplatform/mpfs_hal/startup_gcc/mss_utils.S'
  - 'lib/libplatform/mpfs_hal/startup_gcc/newlib_stubs.c'
  - 'lib/libplatform/mpfs_hal/startup_gcc/system_startup.c'
  
includes:
  - 'lib/libplatform'

